export { useGeTOrders } from './getOrders'
export { useGeTOrderDetail } from './getOrderDetails'
export { useGeTOrderDeliveryLocations } from './getOrderDeliveryLocations'
export { useGetCustomerHistory } from './getClientHistory'
export { useGDiscounts } from './getDiscounts'
export { useGetPropertyOptions } from './getPropertyOptions'

export { useCreateOrder } from './postCreateOrder'
export { useAddDiscountToOrder } from './postAddDiscountToOrder'
export { useAddNoteToOrderDiscussion } from './postAddNoteToOrderDiscussion'
export { useAddPartPayment } from './postAddPartPayment'

export { useUpdateOrderStatus } from './patchUpdateOrderStatus'
export { useUpdateDriverDetails } from './patchUpdateDriverDetails'
export { useUpdateOrderPaymentMethod } from './patchUpdateOrderPaymentMethod'
export { useUpdateDeliveryStatus } from './patchUpdateDeliveryStatus'
export { useUpdatePaymentVerified } from './patchUpdatePaymentVerified'
export { useGetRiderOrders } from './getRiderOrders'
