import type { Metadata } from 'next';
import { DM_Sans, Manrope, Poppins } from 'next/font/google';
import './globals.css';
import { AllProviders } from '@/contexts';

const dmSans = DM_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
});

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});
const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${dmSans.className} ${poppins.variable} ${manrope.variable}`}
      >
        <AllProviders>
          {children}
        </AllProviders>
      </body>
    </html>
  );
}
