import type {Metadata} from 'next';
import {DM_Sans, Poppins} from 'next/font/google';
import './globals.css';

const dmSans = DM_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
});

const poppins = Poppins({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${dmSans.variable} ${poppins.variable}`}
        style={{
          fontFamily: 'var(--font-dm-sans), var(--font-poppins), sans-serif',
        }}>
        {children}
      </body>
    </html>
  );
}
